<a href="https://colab.research.google.com/github/budhathokidinesh/PyTorch/blob/main/00_pytorch_fundamental.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##  oo.PyTorch Fundamentals

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.11.0+cu128


## Introduction to tensors

### Creating tensors
## Pytorch tensors are created using `torch.tensor()` =https://docs.pytorch.org/docs/2.12/tensors.html#torch.Tensor

#scalar

In [3]:


scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
#Get tensor back as Python int
scalar.item()

7

In [6]:
#Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
#MATRIX
MATRIX = torch.tensor([[7,8], [9,1]])
MATRIX

tensor([[7, 8],
        [9, 1]])

In [10]:
MATRIX .ndim

2

In [11]:
MATRIX .shape

torch.Size([2, 2])

In [12]:
MATRIX [1]

tensor([9, 1])

In [13]:
MATRIX [0]

tensor([7, 8])

In [14]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3], [4,5,6], [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR.shape

torch.Size([1, 3, 3])

##Random Tensor
Why rando tensors?
Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

Random tensor -https://docs.pytorch.org/docs/main/generated/torch.rand.html

In [17]:
###Random Tensors
#Create a random tensors of size(3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.3894, 0.5915, 0.9457, 0.9416],
        [0.1376, 0.5003, 0.4049, 0.3769],
        [0.6357, 0.6278, 0.1951, 0.1171]])

In [18]:
random_tensor.ndim

2

In [19]:
random_tensor.shape

torch.Size([3, 4])

In [20]:
#Create a random tensor with similar shape to an image tensor
random_image_size_tenosr =torch.rand(size = (3, 224, 224)) #height, width, colour channels (R, G,B)
random_image_size_tenosr.shape, random_image_size_tenosr.ndim

(torch.Size([3, 224, 224]), 3)

###ZEROS AND ONES

In [21]:
#Create a tensor of all zeros
zeros = torch.zeros(size = (3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [22]:
#Create a tensor of all ones
ones = torch.ones(size = (3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [23]:
ones.dtype

torch.float32

In [24]:
random_tensor.dtype

torch.float32

###Creating a range of tensors and tensors-like


In [25]:
#Use torch.arange
one_to_ten = torch.arange(start = 0, end=1000, step = 50)
one_to_ten

tensor([  0,  50, 100, 150, 200, 250, 300, 350, 400, 450, 500, 550, 600, 650,
        700, 750, 800, 850, 900, 950])

In [26]:
#Creating tensors like
ten_zeros = torch.zeros_like(input = one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

###Tensor datatypes
**Note:** Tensor datatypes is the one of the 3 big errors you'll run into with PyTorch and deep learning:
1. Tensors not right datatypes
2. Tensors not right shape
3. Tensors not on the right device

Precision in Computing -https://en.wikipedia.org/wiki/Precision_(computer_science)

In [27]:
#Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None, #what datatype is the tensor(e.g. float32 or float16)
                               device=None, # What device is your tensor on
                               requires_grad=False) # wheather or not to track gradients with this tensor operations
float_32_tensor

tensor([3., 6., 9.])

In [28]:
float_32_tensor.dtype

torch.float32

In [29]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [30]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [31]:
int_32_tensor = torch.tensor([3,6,9], dtype = torch.int64)
int_32_tensor

tensor([3, 6, 9])

In [32]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensor (Tensor attributes)
1. Tensors not right datatypes -to do get datatype from a tensor can use `tensor.dtype`
2. Tensors not right shape -to get shape from a tensor can use `tensor.shape`
3. Tensors not on the right device -to get device from a tensor can use `tensor.device`

In [33]:
# Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.2803, 0.4935, 0.4952, 0.4922],
        [0.1882, 0.5377, 0.1727, 0.1404],
        [0.9806, 0.2561, 0.3692, 0.0066]])

In [34]:
# Find out some details about tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor:{some_tensor.shape}")
print(f"Device of tensor:{some_tensor.device}")


tensor([[0.2803, 0.4935, 0.4952, 0.4922],
        [0.1882, 0.5377, 0.1727, 0.1404],
        [0.9806, 0.2561, 0.3692, 0.0066]])
Datatype of tensor: torch.float32
Shape of tensor:torch.Size([3, 4])
Device of tensor:cpu


### Manupulating the Tensor
Tensor operation include:
* Addition
* Substraction
* Multipication (Element-wise)
* Division
* Matrix multipication

In [35]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [36]:
# Multiply tensor by 10
tensor = tensor * 10
tensor

tensor([10, 20, 30])

In [37]:
# Substact 10
tensor -10

tensor([ 0, 10, 20])

In [38]:
# Try out PyTorc in-built functions
torch.mul(tensor, 10)

tensor([100, 200, 300])

In [39]:
torch.add(tensor, 10)

tensor([20, 30, 40])

### Matrix multipication
Two main ways of performing multipication in neural networks and deep learning:
1. Element-wise multiication
2. Matrix multipication (dot product)

In [40]:
#Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")


tensor([10, 20, 30]) * tensor([10, 20, 30])
Equals: tensor([100, 400, 900])


In [41]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(1400)

In [42]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(1400)
CPU times: user 0 ns, sys: 1.27 ms, total: 1.27 ms
Wall time: 4.74 ms


In [43]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 693 µs, sys: 0 ns, total: 693 µs
Wall time: 597 µs


tensor(1400)

### There are 2 main rules that performing matrix multiplication need need to satisfy
1. The **inner dimensions** must match
* `(3,2) @ (3,2)` won't work
* `(2,3) @ (3,2)` will work
* `(3,2) @ (2,3)` will work
2. The resulting matrix has the shape of the  **outer dimensions**
 `(2,3) @ (3,2)` -> `(2,2)`

In [44]:
torch.matmul(torch.rand(10,2), torch.rand(2,10)).shape

torch.Size([10, 10])

In [45]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])
tensor_B = torch.tensor([[7,8],
                       [9,10],
                       [11,12]])
#torch.mm(tensor_A, tensor_B) # torch.mm is the same as matmul (it's an alias for the writing less code)
#torch.matmul(tensor_A, tensor_B)

In [46]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [47]:
# To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **Transpose**
tensor_B.T, tensor_B.T.shape


(tensor([[ 7,  9, 11],
         [ 8, 10, 12]]),
 torch.Size([2, 3]))

In [48]:
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

### Finding the min, max, mean, sum etc (tensor aggregation)

In [49]:
# Create a tensor
x = torch.arange(1, 100, 10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [50]:
# Find the min
torch.min(x), x.min()

(tensor(1), tensor(1))

In [51]:
# Find the max
torch.max(x), x.max()

(tensor(91), tensor(91))

In [52]:
# Find the mean -note: the torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [53]:
# Find the sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))

In [54]:
# Finding the positional min and max
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [55]:
# Find the position in the tensor that has the minimum value with argmin() -> returns index position of target tensor where the minimum value occurs
x.argmin()

tensor(0)

In [56]:
# Find the position in the tensor that has maximum value with argmax() -> returns index position of target tensor where the maximum value occurs
x.argmax()

tensor(9)

### Reshaing, stacking, squeezing and unsqueezing tensors

* Reshaping - reshape an input input tensor to a defined shape
* View -Return a view of an inpput tensor of certain shape but keep the same memory
* Stacking -Combine multiple tensors on the top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueez - add a `1` dimension to a target tensor
* Permute -Return a view of the input with dimensions permuted (swapped ) in a certain way

In [57]:
#Lets create a tensor
x = torch.arange(1., 9.)
x, x.shape


(tensor([1., 2., 3., 4., 5., 6., 7., 8.]), torch.Size([8]))

In [58]:
 # Add an extra dimension
x_reshaped = x.reshape(4,2)
x_reshaped, x_reshaped.shape

(tensor([[1., 2.],
         [3., 4.],
         [5., 6.],
         [7., 8.]]),
 torch.Size([4, 2]))

In [59]:
# Change the view
z = x.view(4,2)
z, z.shape

(tensor([[1., 2.],
         [3., 4.],
         [5., 6.],
         [7., 8.]]),
 torch.Size([4, 2]))

In [60]:
# Changing z changes x (because a view of a ensor shares the same memory as the original input)
z[:, 0] = 5
z, x

(tensor([[5., 2.],
         [5., 4.],
         [5., 6.],
         [5., 8.]]),
 tensor([5., 2., 5., 4., 5., 6., 5., 8.]))

In [61]:
# Stack tensors on top each other
x_stacked = torch.stack([x, x, x, x], dim = 1)
x_stacked, x_stacked.shape

(tensor([[5., 5., 5., 5.],
         [2., 2., 2., 2.],
         [5., 5., 5., 5.],
         [4., 4., 4., 4.],
         [5., 5., 5., 5.],
         [6., 6., 6., 6.],
         [5., 5., 5., 5.],
         [8., 8., 8., 8.]]),
 torch.Size([8, 4]))

## Reproductibility (Trying to take random out of random)
 In short how a neural network learns:
  `start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> and again ...`

  To reduce the randomness in neural networks and PyTorch comes the concept of a  **random seed**
  Essentially what the random seed does is "flavour" the randomness.

In [62]:
torch.rand(3,3)

tensor([[0.7565, 0.1815, 0.5880],
        [0.2627, 0.5868, 0.2230],
        [0.8737, 0.3441, 0.3762]])

In [63]:
 # Create two random tensors
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.6493, 0.5810, 0.0027, 0.8964],
        [0.3638, 0.3621, 0.1492, 0.5396],
        [0.4964, 0.4248, 0.0015, 0.1992]])
tensor([[0.3718, 0.7160, 0.5703, 0.1099],
        [0.5758, 0.5967, 0.5947, 0.9632],
        [0.4902, 0.0571, 0.3287, 0.5440]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [64]:
# Lets make some random but reproducible tenosrs
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch objects on the GPUs (and making faster computations)
 GPU = Faster computation on numbers , tanks to CUDA +NVIDIA + PyTorch working behind the scenes to make everything hunky dory

In [65]:
torch.cuda.is_available()

True

In [67]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [68]:
!nvidia-smi

Wed Jun  3 04:19:23 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   32C    P8             10W /   70W |       3MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [69]:
# Count the number of devices
torch.cuda.device_count()

1

In [ ]:
# Putting tensors (and models) on the GPU
# The reason we want our tensors/models on the GPU is because using a GPU results in faster computations.

In [70]:
# Create a tensor (default on the CPU)
tensor = torch.tensor([1, 2, 3], device = "cpu")

#Tensor not on GPU
print(tensor, tensor.device)



tensor([1, 2, 3]) cpu


In [71]:
# Move tensor to GPU (if availabe)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [73]:
#Moving tensor back to the CPU
# If tensor is on GPU,can't transform it to NumPy
# We can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [74]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')